version: '3.8'

services:
  app:
    container_name: node10-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes: 
      - ./:/app:delegated
      - /app/node_modules
